name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          
      - name: ensure assets folder exists
        run: mkdir -p assets

      - name: move generated SVG to assets
        run: cp dist/github-snake.svg assets/github-snake.svg

      - name: push github-contribution-grid-snake.svg to the main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snake Animation"
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
